### PR TITLE
add c utf8 TextDecoder/TextEncoder implementation

### PR DESCRIPTION
**Pull request by lal12**
Probably not the most efficient implementation, but ofc still much quicker than the JS implementation before.
It follows the spec pseudo code: https://encoding.spec.whatwg.org/

There is a patch needed for quickjs to expose some internal functionality. I will look further review the patch and submit it when I get a go ahead here.

[expose_string_internals.zip](https://github.com/saghul/txiki.js/files/13925224/expose_string_internals.zip) (Github doesn't allow me to upload the patch file directly :roll_eyes: )

Regarding to #447

### CODE REVIEW

**Comment by lal12** [comment]
Hey @saghul, any time estimates on reviewing it?

**Comment by saghul** [comment]
I hope to get some cycles next week, sorry!

**Comment by lal12** [comment]
> I hope to get some cycles next week, sorry!

No worries, just wanted to know for some "planability" for me.

**Comment by saghul** [comment]
So sorry for the delay, life got on the way...

I finally had a chance to look at the internals patch. I'm afraid that is not something we want to expose in QuickJS. Replacing the internal string implementation with ropes is on the cards, and exposing the internals would put us in a precarious situation API-wise.

Let's continue the discussion in #447

**Pull request closed without merging**
