### PR TITLE
core: fix timers typo

### PR DESCRIPTION
**Pull request by topelinux**
fix clearInterval typo

### CODE REVIEW

**Comment by saghul** [comment]
🤦

**Comment by saghul** [comment]
Can you regenerate the bytecode? make js and commit the result.

**Comment by topelinux** [comment]
> Can you regenerate the bytecode? make js and commit the result.

done, please review again.

**Comment by saghul** [comment]
Looks like there is a mismatch. You can try again by making sure to use Node 20 or I can help later today!

**Comment by topelinux** [comment]
> Looks like there is a mismatch. You can try again by making sure to use Node 20 or I can help later today!

i have try with node 20.5.1, same result(make js no different with git status), maybe there is something i missed, please help to commit on your side.

**Comment by saghul** [comment]
Created https://github.com/saghul/txiki.js/pull/509 since I cannot push to your repo. The commit author is still you.

**Pull request closed without merging**
