### PR TITLE
fixed memory leak issue in xhr implementation

### PR DESCRIPTION
**Pull request by b0bleet**
AddressSanitizer reported that data and header buffer (`x->result.hbuf` and `x->result.bbuf`) were never deallocated after being used in XHR constructor. There should be dbuf_dealloc in tjs_xhr_finalizer to do deallocation.
```
=================================================================
==207138==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 253 byte(s) in 1 object(s) allocated from:
    #0 0x7f411cac6c3e in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:163
    #1 0x55984f710542 in dbuf_realloc /tmp/txiki.js/deps/quickjs/src/cutils.c:114
    #2 0x55984f710542 in dbuf_put /tmp/txiki.js/deps/quickjs/src/cutils.c:140
    #3 0x55984f70acdc in curl__data_cb /tmp/txiki.js/src/xhr.c:212
    #4 0x7f411c7f65ae  (/lib/x86_64-linux-gnu/libcurl.so.4+0x1d5ae)
    #5 0x7f411c8089ca  (/lib/x86_64-linux-gnu/libcurl.so.4+0x2f9ca)
    #6 0x7f411c8125f3  (/lib/x86_64-linux-gnu/libcurl.so.4+0x395f3)
    #7 0x7f411c813c9b  (/lib/x86_64-linux-gnu/libcurl.so.4+0x3ac9b)
    #8 0x7f411c813e37 in curl_multi_socket_action (/lib/x86_64-linux-gnu/libcurl.so.4+0x3ae37)
    #9 0x55984f6e4d49 in uv__poll_cb /tmp/txiki.js/src/curl-utils.c:151
    #10 0x55984f7f1124 in uv__io_poll /tmp/txiki.js/deps/libuv/src/unix/epoll.c:374
    #11 0x55984f7dd9d1 in uv_run /tmp/txiki.js/deps/libuv/src/unix/core.c:391
    #12 0x55984f7050c8 in TJS_Run /tmp/txiki.js/src/vm.c:358
    #13 0x55984f6e3ca1 in main /tmp/txiki.js/src/cli.c:173
    #14 0x7f411c5d60b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #15 0x55984f6e41fd in _start (/tmp/txiki.js/build/tjs+0x2d1fd)

Direct leak of 231 byte(s) in 1 object(s) allocated from:
    #0 0x7f411cac6c3e in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:163
    #1 0x55984f710542 in dbuf_realloc /tmp/txiki.js/deps/quickjs/src/cutils.c:114
    #2 0x55984f710542 in dbuf_put /tmp/txiki.js/deps/quickjs/src/cutils.c:140
    #3 0x55984f70a90a in curl__header_cb /tmp/txiki.js/src/xhr.c:263
    #4 0x7f411c7f6610  (/lib/x86_64-linux-gnu/libcurl.so.4+0x1d610)
    #5 0x7f411c7f4b89  (/lib/x86_64-linux-gnu/libcurl.so.4+0x1bb89)
    #6 0x7f411c807f4e  (/lib/x86_64-linux-gnu/libcurl.so.4+0x2ef4e)
    #7 0x7f411c8125f3  (/lib/x86_64-linux-gnu/libcurl.so.4+0x395f3)
    #8 0x7f411c813c9b  (/lib/x86_64-linux-gnu/libcurl.so.4+0x3ac9b)
    #9 0x7f411c813e37 in curl_multi_socket_action (/lib/x86_64-linux-gnu/libcurl.so.4+0x3ae37)
    #10 0x55984f6e4d49 in uv__poll_cb /tmp/txiki.js/src/curl-utils.c:151
    #11 0x55984f7f1124 in uv__io_poll /tmp/txiki.js/deps/libuv/src/unix/epoll.c:374
    #12 0x55984f7dd9d1 in uv_run /tmp/txiki.js/deps/libuv/src/unix/core.c:391
    #13 0x55984f7050c8 in TJS_Run /tmp/txiki.js/src/vm.c:358
    #14 0x55984f6e3ca1 in main /tmp/txiki.js/src/cli.c:173
    #15 0x7f411c5d60b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #16 0x55984f6e41fd in _start (/tmp/txiki.js/build/tjs+0x2d1fd)

```

### CODE REVIEW

**Comment by saghul** [comment]
The fix looks good but the removal of cli.c kinda breaks the project :-)

**Comment by b0bleet** [comment]
Sorry @saghul I've deleted that file for custom my project but this commit was affected by that. You can ignore this change (deletion of cli.c).

**Comment by saghul** [comment]
LGTM, how did you find it? I cannot seem to trigger it. This is how I modified txikijs to build with ASAN:

~~~
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 437cc85..973a49c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -42,6 +42,8 @@ macro(cpr_option OPTION_NAME OPTION_TEXT OPTION_DEFAULT)
     message(STATUS "  ${OPTION_NAME}: ${${OPTION_NAME}}")
 endmacro()
 
+cpr_option(BUILD_WITH_ASAN "If ON, build with the address sanitizer enabled" OFF)
+
 configure_file(
         ${CMAKE_SOURCE_DIR}/src/js/bundle.js
         ${CMAKE_CURRENT_BINARY_DIR}/bundle.js
@@ -110,3 +112,8 @@ target_link_libraries(tjs qjs uv_a m3 m ${CURL_LIBRARIES})
 if(MINGW)
     target_link_libraries(tjs pthread)
 endif()
+
+if (BUILD_WITH_ASAN)
+    target_compile_options(tjs PRIVATE -fsanitize=address)
+    target_link_options(tjs PRIVATE -fsanitize=address)
+endif()

~~~

**Comment by saghul** [comment]
Not sure why I couldn't repro on macOS, but I can on Linux.

**Comment by b0bleet** [comment]
> Not sure why I couldn't repro on macOS, but I can on Linux.
Yes, I tried on macOS as well but I did not get ASAN message.

**Pull request closed without merging**
