### PR TITLE
Fix segfault by twice calling curl_easy_cleanup() at async mode.

### PR DESCRIPTION
**Pull request by junsik**

### CODE REVIEW

**Comment by junsik** [comment]
Sorry, I found a bug. :(

**Comment by saghul** [comment]
No worries. Can you please remove the first commit? It already landed and it causes a conflict. Bonus points if you add a regression test!

**Comment by junsik** [comment]
Sorry for late response. I am not used to github.
It looks like fixed. But travis-ci build failed by test-performance.js. :(
Do I need to close this and re-create the pull-request again?

**Comment by saghul** [comment]
No worries, that test is a bit flaky. Now, any chance you can add a test which crashes without your fix but passes with it?

**Comment by saghul** [comment]
I landed your patch in ca1890b, cheers!

**Pull request closed without merging**
