### PR TITLE
process: added exec(cmd) wrapper around execvp()

### PR DESCRIPTION
**Pull request by samuelbrian**
Hi @saghul,

I've been using tjs for scripting in an embedded Linux environment, and although there is no libuv helper function, being able to exec is pretty useful.

### CODE REVIEW

**Comment by samuelbrian** [comment]
In short, I'm using tjs as an alternative to shell for system service scripts that read/write JSON.

I've got a program that runs system services, sort of like an init, and it keeps track of each service process's pid so that it can be sent signals.
These service processes are generally shell scripts, and more recently tjs scripts, which write configuration files and then start a daemon.

If the script spawns the daemon as a subprocess with the daemon foregrounded, then the script has to keep running and wait on the daemon and proxy signals to it.

If the script spawns the daemon as a subprocess with the daemon backgrounding itself, then it must exit and deal with pidfiles when it is run again to restart or SIGHUP the daemon.

If the script execs into the daemon (foregrounded), then I can take advantage of the killing logic in the system runner and avoid a process hanging around with such a minimal purpose.

I'm not sure if exec() is useful to all, but it's in enough of other language's runtimes/stdlib so I thought it might be a good fit.
No worries if you don't want to take it. I keep some patches for other things I expect have no chance of being accepted, like a more complicated module resolution that works sort of like nodejs and searches paths listed in the env variable `TJS_LIBRARY_PATH` which defaults to `/lib/js`.

**Comment by saghul** [comment]
Would exposing the UV_PROCESS_DETACHED flag for spawn help? Or would that be case 2 in your list?

I'm a bit hesitant on this one since it opens the window for platform dependent stuff I'm not sure I want to add. I'll say I am surprised it just worked on MinGW :-)

Let me think about this one some more.

**Comment by samuelbrian** [comment]
Yep, UV_PROCESS_DETACHED is case 2.

I sat on this change for a while because originally I was using execvpe() which wasn't available on MacOS or MinGW.
But since ditching the env setting and using execvp() and getting it working on all the CI platforms I thought it had a shot :)

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Let's have it.

**Pull request merged**
