### PR TITLE
autoconf, textinfo dependencies Debian/Ubuntu

### PR DESCRIPTION
**Pull request by guest271314**
autoconf for autoreconf, textinfo for makeinfo dependencies Debian/Ubuntu

### CODE REVIEW

**Comment by saghul** [comment]
Do you have suggested / recommended packages disables? I think those should be dependencies of build-essential.

**Comment by guest271314** [comment]
This list was generated on Sun 03 Jan 2021 11:30:56 AM CET for amd64
It contains a list of essential packages (which are also build-essential).

From `/usr/share/build-essential/essential-packages-list`

```
base-files
base-passwd
bash
bsdutils
coreutils
dash
debianutils
diffutils
dpkg
findutils
grep
gzip
hostname
init-system-helpers
libc-bin
login
ncurses-base
ncurses-bin
perl-base
sed
sysvinit-utils
tar
util-linux
```

**Comment by guest271314** [comment]
`apt cache show` does not list `autoconf` (`autoreconf` is called during the build) or `texinfo` as "Build-Essential: yes". I suggest testing OS, update, install build-essential then run `make` without the autoconf and makeinfo or texinfo installed to check if errors are thrown.

**Comment by saghul** [comment]
Thanks for looking into it. I'll give it a try, thanks!

**Comment by guest271314** [comment]
`autoconf`, `texinfo`, `libtool` are not in `build-essential` on Debian 12.

**Comment by saghul** [comment]
Ops this feel the ought the cracks sorry!

This is only necessary when using the bundled libffi, right?

**Comment by guest271314** [comment]
I think so. If you omit installing  them, then install one by one you'll get an error for each - no libtool, error, no autoconf no autoreconf, error, no texinfo, errror. 

Ubuntu right now is whole 'nother ball of wax. I used to be able to install buil-essential and cmal and gcc on Xubuntu live USB. Build tks at least dozens of time. After around 2 months ago, following this commit https://github.com/guest271314/telnet-client/commit/18a332f179703a35080beedf3834c3dc42ba4132 everytime I tried to install build-essential or cmake or gcc the machine crashed. I think it has something to do with Ubuntu trying to move more to snap, but I'm not sure. So I went back to Debian.

When you find the time I would fetch Ubuntu's latest LTS and Debian's latest releast and test what I describe above for your own independent verification.

These dependencies are not automatically included in the distribution and at least for me something changed in Ubunto world over he past couple months which made it essentially impossible to build txiki.js on a live USB.

**Comment by guest271314** [comment]
On Debian 12 - _without_ installing `autoconf` for `autoreconf`, `texinfo` for `makeinfo`, not the errors before exit

```
$ make
...
[ 62%] Linking C static library libqjs.a
gmake[3]: Leaving directory '/home/user/bin/txiki.js/build'
[ 62%] Built target qjs
gmake[2]: Leaving directory '/home/user/bin/txiki.js/build'
gmake[1]: *** [Makefile:136: all] Error 2
gmake[1]: Leaving directory '/home/user/bin/txiki.js/build'
make: *** [Makefile:10: build] Error 2
```

After installing `autoconf` and `texinfo` we still get errors because of `libtool` dependency

```
$ make
...
configure.ac:41: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:8529: error: possibly undefined macro: AC_PROG_LD
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
gmake[3]: *** [CMakeFiles/libffi.dir/build.make:92: libffi-prefix/src/libffi-stamp/libffi-configure] Error 1
gmake[3]: Leaving directory '/home/user/bin/txiki.js/build'
gmake[2]: *** [CMakeFiles/Makefile2:254: CMakeFiles/libffi.dir/all] Error 2
gmake[2]: *** Waiting for unfinished jobs....
[ 62%] Linking C static library libsqlite3.a
gmake[3]: Leaving directory '/home/user/bin/txiki.js/build'
[ 62%] Built target sqlite3
gmake[2]: Leaving directory '/home/user/bin/txiki.js/build'
gmake[1]: *** [Makefile:136: all] Error 2
gmake[1]: Leaving directory '/home/user/bin/txiki.js/build'
make: *** [Makefile:10: build] Error 2
```

After installing `libtool` `tjs` gets built successfully, no errors. So `libtool` needs to be added to the list, too, given the suggested installation in the README

```
$ make
...
[ 98%] Building C object CMakeFiles/tjs.dir/src/posix-socket.c.o
[100%] Linking C executable tjs
gmake[3]: Leaving directory '/home/user/bin/txiki.js/build'
[100%] Built target tjs
gmake[2]: Leaving directory '/home/user/bin/txiki.js/build'
gmake[1]: Leaving directory '/home/user/bin/txiki.js/build'
```

**Comment by saghul** [comment]
Thanks for the details! Can you update the PR! I'll merge it then.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Thank you!

**Pull request merged**
