### PR TITLE
core: introduce tjs.engine

### PR DESCRIPTION
**Pull request by saghul**
It includes the bytecode manipulation functions in addition to the versions object.

This will be the namespace to add engine specific stuff, like the engine memory usage, for example.

~~TODO: docs.~~

### CODE REVIEW

**Comment by KaruroChori** [comment]
This regressed/reverted the gc object PR I added few weeks ago features, but tests have not been changed to show that.
Either way it should be fixed.

**Comment by KaruroChori** [comment]
Also, the documentation generated from ts.d will only nest children on the left tree view for `namespaces`. It might be worth to declare `tjs.engine` as such, so that its first-level entries will be shown directly on the menu.

**Comment by saghul** [comment]
> The interface in the types file is incomplete for some reason which threw me off. Might it be that I missed to push a commit on that occasion?

Probably yeah!

> Also, the documentation generated from `ts.d` files will only nest children on the left tree view for `namespaces`, not for interfaces. It might be worth to declare `tjs.engine` as such, so that its first-level entries will be shown directly on the menu.

Hum, I'll take a look at that, thanks for the heads up!

**Comment by saghul** [comment]
Screenshot 2024-07-08 at 16 44 46

Looks like it's OK? I see the interfaces as members of the tjs namespace on the left bar.

**Comment by KaruroChori** [comment]
Yes, what I was saying is that its children are not shown as a nested menu.
Since `tjs.engine` is effectively just serving as namespace, it would have made sense to handle it as such from a typing perspective, and so tsdoc would have generated a subfolder in the menu for its children.

**Comment by saghul** [comment]
Gotcha. Since that was kinda there already, I'll take a look at it all together in a separate PR 👍

**Pull request merged**
