### PR TITLE
add patch for text-encoding-utf-8, support utf8

### PR DESCRIPTION
**Pull request by ahaoboy**
close: https://github.com/saghul/txiki.js/issues/630
If there is a better solution, please close this PR

### CODE REVIEW

**Comment by ahaoboy** [comment]
Why use window instead of global This as the global object? Is it because events can be listened on window?

**Comment by saghul** [comment]
We already use patch-package on the polyfill, can you please apply the patch there instead?

**Comment by saghul** [comment]
> Why use window instead of globalThis as the global object? Is it because events can be listened on window?

Out of habit, but yeah this should be globalThis.

**Comment by ahaoboy** [comment]
> We already use patch-package on the polyfill, can you please apply the patch there instead?

done

**Comment by ahaoboy** [comment]
The behavior of patch-package is a bit strange, I may need to investigate further, and it seems that after installing patch, the compilation result of make js && make does not change, which is a bit strange

**Comment by saghul** [comment]
Yeah when the polyfills change the Makefile doesn't quite pick it up because the dependencies across files are not detected.

You can force it by deleting the .c file.

**Comment by ahaoboy** [comment]
What's strange is that this patch doesn't seem to modify the source code, so why is it added here?
Is it because the editor automatically formats it?
```patch
@@ -639,4 +640,4 @@ function UTF8Encoder(options) {
 }
 
 exports.TextEncoder = TextEncoder;
-exports.TextDecoder = TextDecoder;
\ No newline at end of file
+exports.TextDecoder = TextDecoder;
```

I only added an alias utf8, which should cover most usage scenarios.

**Comment by saghul** [comment]
Thank you!

**Pull request merged**
