### PR TITLE
Update to latest quickjs release

### PR DESCRIPTION
**Pull request by johnrobinsn**
* Update to latest quickjs release 2021-03-27
* generate a static library 'quv' for the core libuv runtime support for embedding purposes.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks! Can you please break this into 2 PRs? We do want to update, but I'm not yet sure about the extra target.

**Comment by johnrobinsn** [comment]
Ok.  I'm embedding the quv lib into another project.  So I think a useful addition.  But will split them apart.

**Comment by saghul** [comment]
Right. In that case let's have it, but separate please. It should be called libtjs, since quv was a short lived previous name this project had.

**Comment by johnrobinsn** [comment]
Makes sense... closing this PR and will open new ones

**Comment by saghul** [comment]
Thank you!

**Pull request closed without merging**
